Repository mavenlink/mavenlink_gem, pull requests merged in 2018-08, with the labels that each got.

#85 Add `backup_approver_association` to Mavenlink model
  lib/config/specification.yml
  lib/mavenlink.rb
  lib/mavenlink/backup_approver_association.rb
  spec/lib/mavenlink/account_membership_spec.rb
  spec/lib/mavenlink/backup_approver_association_spec.rb
Labels: LGTM, enhancement, reviewable

#86 Add time off entries
  lib/config/specification.yml
  lib/mavenlink.rb
  lib/mavenlink/time_off_entry.rb
  spec/lib/mavenlink/time_off_entry_spec.rb
Labels: enhancement, reviewable

#87 add external_status to external_reference
  lib/config/specification.yml
Labels: LGTM, enhancement

#89 Add missing custom field attributes
  lib/config/specification.yml
Labels: enhancement
