Repository mavenlink/mavenlink_gem, pull requests merged in 2020-08, with the labels that each got.

#160 Add external_references to time_adjustments
  lib/config/specification.yml
  spec/lib/mavenlink/time_adjustment_spec.rb
Labels: reviewable

#161 Update custom field attributes and associations
  lib/config/specification.yml
  spec/lib/mavenlink/custom_field_spec.rb
Labels: reviewable

#162 Fix broken association definitions
  lib/config/specification.yml
Labels: bug

#159 Add project accounting record
  lib/config/specification.yml
  lib/mavenlink.rb
  lib/mavenlink/project_accounting_record.rb
  spec/lib/mavenlink/project_accounting_record_spec.rb
Labels: enhancement, reviewable

#163 add auto-update-label to update workspace resources
  lib/config/specification.yml
Labels: QA - Dev QA ✓, reviewable

#164 Update Workspace Allocations
  lib/config/specification.yml
  spec/lib/mavenlink/workspace_allocation_spec.rb
Labels: reviewable
