Repository mavenlink/mavenlink_gem, pull requests merged in 2020-11, with the labels that each got.

#167 add external references to vendors
  lib/config/specification.yml
Labels: blocked, reviewable

#168 Add skill adjacency model
  lib/config/specification.yml
  lib/mavenlink.rb
  lib/mavenlink/skill_adjacency.rb
  spec/lib/mavenlink/skill_adjacency_spec.rb
Labels: reviewable

#170 Vendor - add external references to create and update
  lib/config/specification.yml
Labels: reviewable

#169 Update Participation Attributes/Associations
  lib/config/specification.yml
  spec/lib/mavenlink/participation_spec.rb
Labels: reviewable

#171 Add external references to assigments
  lib/config/specification.yml
  spec/lib/mavenlink/assignment_spec.rb
Labels: QA - Dev QA ✓, reviewable
