Repository mavenlink/mavenlink_gem, pull requests merged in 2020-05, with the labels that each got.

#148 Specify all_on_account when reloading story associations
  lib/mavenlink/story.rb
  spec/lib/mavenlink/story_spec.rb
Labels: bug, reviewable

#149 Fix model reloading and associations
  lib/mavenlink/model.rb
  lib/mavenlink/request.rb
  lib/mavenlink/response.rb
  lib/mavenlink/story.rb
  spec/lib/mavenlink/client_spec.rb
  spec/lib/mavenlink/model_spec.rb
  spec/lib/mavenlink/request_spec.rb
  spec/lib/mavenlink/story_spec.rb
  spec/lib/mavenlink/workspace_spec.rb
Labels: reviewable

#150 Call deep_dup on model scope
  lib/mavenlink.rb
  lib/mavenlink/model.rb
Labels: reviewable

#152 Revert "Add show method to use object/id on endpoints"
  lib/mavenlink/model.rb
  lib/mavenlink/request.rb
  spec/lib/mavenlink/client_spec.rb
  spec/lib/mavenlink/model_spec.rb
  spec/lib/mavenlink/request_spec.rb
  spec/lib/mavenlink/workspace_spec.rb
Labels: reviewable

#153 Update Mavenlink Gem to reflect new External Reference Support
  lib/config/specification.yml
  spec/lib/mavenlink/time_off_entry_spec.rb
Labels: QA - Dev QA ✓, reviewable

#154 Update association reload logic to reload if not in response or cache
  lib/mavenlink/model.rb
Labels: QA - Dev QA ✓, reviewable

#151 add external_references to workspace_allocations
  lib/config/specification.yml
  spec/lib/mavenlink/workspace_allocation_spec.rb
Labels: enhancement

#155 add recent_submission association to time_entries
  lib/config/specification.yml
  spec/lib/mavenlink/expense_spec.rb
  spec/lib/mavenlink/time_entry_spec.rb
Labels: LGTM, QA - Dev QA ✓
