Repository mavenlink/mavenlink_gem, pull requests merged in 2021-07, with the labels that each got.

#183 Add missing external_reference attributes
  lib/config/specification.yml
Labels: reviewable

#184 Fix Typo in Rate Card Sets Associations
  lib/config/specification.yml
Labels: bug

#186 add story_followers to specification file
  lib/config/specification.yml
  lib/mavenlink.rb
  lib/mavenlink/story_follow.rb
  spec/lib/mavenlink/story_follow_spec.rb
Labels: QA - Dev QA ✓, enhancement, reviewable

#187 Add story foreign_exchange_cost_budget
  lib/config/specification.yml
Labels: reviewable
