Repository mavenlink/mavenlink_gem, pull requests merged in 2022-05, with the labels that each got.

#223 Revert "Revert "add external references to invoices""
  lib/config/specification.yml
Labels: reviewable

#224 Add Split Endpoint Call to Workspace Allocations
  lib/mavenlink/workspace_allocation.rb
  spec/lib/mavenlink/workspace_allocation_spec.rb
Labels: reviewable, QA - Dev QA ✓

#227 add approver_ids to create/update attributes
  lib/config/specification.yml
Labels: bug
