Repository mavenlink/mavenlink_gem, pull requests merged in 2022-03, with the labels that each got.

#216 Fix primary_workspace_group_id attributes
  lib/config/specification.yml
Labels: reviewable

#217 add external references to invoices
  lib/config/specification.yml
Labels: enhancement

#218 Revert "add external references to invoices"
  lib/config/specification.yml
Labels: bug
